### ISSUE TITLE
Add support for transparent backgrounds in bitmap-to-scad

### ISSUE THREAD

**Issue by smithdtyler** [tactile-graphics/3d-printing-tools#1]
The bitmap-to-scad script currently fails to detect content properly for images with transparent backgrounds instead of white. Update the tool to work with either white or transparent backgrounds. 

@funkonaut could you post your sample file on this ticket?

**Comment by funkonaut** [comment]
![braille-font-test](https://user-images.githubusercontent.com/5996291/151407256-86e13b17-a815-4b45-95c5-2e619cee1540.png)

**Comment by smithdtyler** [comment]
Weird, github seems to have converted this to an RBG image instead of RBGA. No worries, I'll whip up my own test with Inkscape, I'll just need you to check to make sure it works for you as well.

**Comment by smithdtyler** [comment]
Should be fixed via 125f2f72846e2ff8918eaaee64d9605aa39ec196

@funkonaut please try it out and me know if it meets your needs.
