### ISSUE TITLE
Add scad to STL conversion to scripts

### ISSUE THREAD

**Issue by smithdtyler** [tactile-graphics/3d-printing-tools#3]
@funkonaut noted a couple of available command line tools in the [PDF example walkthrough](https://github.com/tactile-graphics/3d-printing-tools/blob/main/doc/examples/pdf/print-from-pdf.md). 

In particular

`openscad -o ./braille-font-test.stl ./doc/examples/pdf/resources/braille-font-test.scad`

Decide if and how to incorporate this into a new or existing script, presumably something like `bitmap-to-stl.sh`

**Comment by smithdtyler** [comment]
I'm having trouble finding the command line api in the OS X release of OpenSCAD.

**Comment by funkonaut** [comment]
I believe if you have installed openSCAD from a .dmg you can right click the application icon to show package contents the executable you should add to your path for openSCAD command line tools should be in the folder {path to openSCAD app}/Contents/MacOS/OpenSCAD if you installed using brew you will have to look for it in where ever your brew package manager install executables. Or it might auto add to your path not sure...

**Comment by smithdtyler** [comment]
Aha! Thanks!

**Comment by smithdtyler** [comment]
Done in b3a23a74de4de1f86f8364d9ced497701b8b7e35

I added a bash script for OS X and Linux. Windows users just need to add -stl to the arguments to bitmap_to_scad.py
